### ISSUE TITLE
Winston 3.x and splat

### ISSUE THREAD

**Issue by olivierto** [lazywithclass/winston-cloudwatch#101]
Hello, i'm using Winston 3.1.0 for logging in console with custom logFormat. 
it seems when variable are passed to the logger the winton cloudwatch formatter doesn't apply the "splat" to the log. 
example : 
```javascript
logger.debug('my name is %s',username);
```
produce a log in cloudwatch : 
```javascript
my name is %s
```
here is my code : 
```javascript
const { createLogger, format, transports, config} = require('winston');
const { combine, timestamp, label, printf } = format;
import winstonCloudWatch from "winston-cloudwatch";
import appConfig from '../config';

let descriptionLoggers = [];
const attestisFormat = printf(info => {
  return `${info.timestamp} [${appConfig.get('env')}] ${info.level}: ${info.message}`;
})


let logFormat = combine(
    format.splat(),
    format.json()
  )

descriptionLoggers.push(new transports.Console({
  timestamp: function () {
    return new Date().toISOString();
  },
  level: appConfig.get('log.consoleLoglevel'),
  colorize: appConfig.get('log.colorize'),
  handleExceptions: true,
  humanReadableUnhandledException: true,
  format: logFormat
}));
descriptionLoggers.push(new winstonCloudWatch({
    name: appConfig.get('env'),
    logGroupName: 'application-log',
    logStreamName: '[API-JO] ' + appConfig.get('env'),
    awsRegion: 'eu-west-3',
    jsonFormat: true
  }));

const logger =  createLogger({
  levels: config.syslog.levels,
  transports: descriptionLoggers,
  exitOnError: false
});

module.exports = logger;
```
i've also tried with the messageFormatter options with no success 
```javascript
descriptionLoggers.push(new winstonCloudWatch({
    name: appConfig.get('env'),
    logGroupName: 'application-log',
    logStreamName: '[API-JO] ' + appConfig.get('env'),
    awsRegion: 'eu-west-3',
    messageFormatter: (log)=>{
      console.log("the log object from winston",log)
      return log.message.toString()
    },
    jsonFormat: true
  }));
```
buy my console log is logging  : 
```javascript
the log object from winston:  {   message: 'my name is %s',
  level: 'debug',
  [Symbol(level)]: 'debug',
  [Symbol(splat)]: ['olivier']
```

Is this a bug or something i'm missing?  do i need to manually apply splat data in the function?

Thanks for your help.

**Comment by bjornSayers** [comment]
I'm experiencing the same issue - cannot figure out how to get splat() to work with this transport

**Comment by bjornSayers** [comment]
So I'm planning on using the following workaround:
`	

const { format } = require('winston');
const { combine, timestamp, printf, colorize, json, splat } = format;
new WinstonCloudWatch({
		logGroupName: awsCloudWatchConfig.logGroupName,
		logStreamName: 'straight_winston_test',
		awsRegion: awsCloudWatchConfig.awsConfig.region,
		awsAccessKeyId: awsCloudWatchConfig.awsConfig.accessKeyId,
		awsSecretKey: awsCloudWatchConfig.awsConfig.secretAccessKey,
		messageFormatter: function(item) {
			const transformedItem = splat().transform(item);

			return `${transformedItem.level}: ${transformedItem.message} ${JSON.stringify(transformedItem)}`;
		}
	})`

I'm open to hearing concerns/improvements.

**Comment by lazywithclass** [comment]
Yes that's why `messageFormatter` has been implemented!
