### ISSUE TITLE
TypeError: winston_cloudwatch_1.default is not a constructor

### ISSUE THREAD

**Issue by jucksearm** [lazywithclass/winston-cloudwatch#104]
use code in typescript
import * as winston from 'winston'
import WinstonCloudWatch from 'winston-cloudwatch'
export default winston.add(new WinstonCloudWatch({}))

after run tsc 
TypeError: winston_cloudwatch_1.default is not a constructor
    at Object.<anonymous> (D:\node-project\ais-cdg-gateway\build\utils\logger.js:5:31)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

**Comment by giomarino** [comment]
I have the same issue. When I remove .default on built JS file everything works. Is it possible to deny .default generation?

**Comment by perbergland** [comment]
Hmmm do you really get that to compile? For me that results in `Cannot use 'new' with an expression whose type lacks a call or construct signature.` for the `new WinstonCloudWatch` call. The typescript definition for the main class seems pretty broken, sadly.

**Comment by perbergland** [comment]
This compiles but crashes because the typescript export doesn’t match the actual export:

       transports.push(new WinstonCloudWatch.default(cwOptions));

**Comment by FrederikPriede** [comment]
I am having the same issue.

**Comment by skam22** [comment]
still having this same issue - any suggested fixes?

**Comment by dwilt** [comment]
In an ES6 node project and [@parque-docs's solution[(https://github.com/lazywithclass/winston-cloudwatch/issues/104#issuecomment-494011013) is what only worked for me. Any reason why the docs shouldn't be updated?

**Comment by sb-pramod92** [comment]
Hi @lazywithclass , still I am facing this error.

(node:17287) UnhandledPromiseRejectionWarning: TypeError: winston_cloudwatch_1.default is not a constructor

tsconfig.json
![image](https://user-images.githubusercontent.com/73944156/202393516-0af79fbd-e82f-4a95-87ed-c9117e74eb56.png)

main.ts
![image](https://user-images.githubusercontent.com/73944156/202393717-8b50ac7c-c603-41ac-8ffb-21a4f7340903.png)


Please let me know if anything I am missing.

Thanks
Pramod Tolani

**Comment by lazywithclass** [comment]
@dwilt No, other than that's an error :D, I've just updated it. Thanks.

**Comment by tom10271** [comment]
I am still getting `WinstonCloudWatch is not a constructor` with `import * as WinstonCloudWatch from 'winston-cloudwatch';`
