### ISSUE TITLE
rententionInDays missing in the type definition

### ISSUE THREAD

**Issue by visheshd** [lazywithclass/winston-cloudwatch#113]
Based on this [example](
https://github.com/lazywithclass/winston-cloudwatch/blob/f04ea514038667ea8c222e5a54f224195948d637/examples/retention-policy.js)

```javascript
var winston = require('winston'),
    WinstonCloudWatch = require('../index');


// when you don't provide a name the default one
// is CloudWatch
winston.add(new WinstonCloudWatch({
  logGroupName: 'testing',
  logStreamName: 'another',
  awsRegion: 'us-east-1',
  retentionInDays: 14
}))

winston.error('1');

```

The [types](https://github.com/lazywithclass/winston-cloudwatch/blob/master/typescript/winston-cloudwatch.d.ts#L49) are missing retentionInDays

**Comment by lazywithclass** [comment]
Addressed in #106, thanks anyway for your PR!
