### ISSUE TITLE
Dependency https-proxy-agent vulnerabilty

### ISSUE THREAD

**Issue by mlisonek98** [lazywithclass/winston-cloudwatch#119]
Hey so there apparently is a security issue with older versions of https-proxy-agent which is a dependency of this package. Any way it can be updated to version 3.0.0? Here is what . i get when I run npm audit:
`                       === npm audit security report ===                        

                             Manual Review
       Some vulnerabilities require your attention to resolve
     Visit https://go.npm.me/audit-guide for additional guidance
High          │ Machine-In-The-Middle                         
Package       │ https-proxy-agent                 
Patched in    │ >=3.0.0               
Dependency of │ winston-cloudwatch          
 Path          │ winston-cloudwatch > proxy-agent > https-proxy-agent     
 More info     │ https://nodesecurity.io/advisories/1184        
High          │ Machine-In-The-Middle                
Package       │ https-proxy-agent                             
Patched in    │ >=3.0.0                                                      
 Dependency of │ winston-cloudwatch                                   
 Path          │ winston-cloudwatch > proxy-agent > pac-proxy-agent >         
               │ https-proxy-agent                                            
│ More info     │ https://nodesecurity.io/advisories/1184     `

**Comment by lazywithclass** [comment]
Yes, tonight I will deal with two other issues and I'll update dependencies, this got postponed for too long.

**Comment by mlisonek98** [comment]
Thanks! great package btw

**Comment by lazywithclass** [comment]
The package has many issues, but thanks! :D

winston-cloudwatch@2.1.0 has updated dependencies.
