### ISSUE TITLE
InvalidSequenceTokenException: The given sequenceToken is invalid

### ISSUE THREAD

**Issue by bburket** [lazywithclass/winston-cloudwatch#12]
Full exception:

{ [InvalidSequenceTokenException: The given sequenceToken is invalid. The next expected sequenceToken is: 49547819323650541342942483991180069050112003840413809090]
  message: 'The given sequenceToken is invalid. The next expected sequenceToken is: 49547819323650541342942483991180069050112003840413809090',
  code: 'InvalidSequenceTokenException',
  time: Mon Mar 16 2015 22:51:26 GMT+0000 (UTC),
  statusCode: 400,
  retryable: false,
  retryDelay: 30 }

This happens when running NodeJs in "clustered" mode (using .fork() to host multiple simultaneous processes). However this issue would reproduce in two separate machines as well, assuming the machines shared the same log group and log stream.

**Comment by theRealGabacho** [comment]
Note: It would be possible to use a dynamically generated log stream name, but due to the problem encountered in issue #11, this is difficult

**Comment by lazywithclass** [comment]
I think there should be a way to retry this, as far as I've understood it that error means CloudWatch Logs has received more requests than we are allowed to send, so it refuses.

I'll have a look at implementing a retry policy during the weekend.

**Comment by lazywithclass** [comment]
I'm testing this library at work in a spiked environment, I've identified a couple silly mistakes by me and addressed them.
Those fixes along with a few other changes from @machinemetrics could be found [here](https://github.com/lazywithclass/winston-cloudwatch/blob/improvements-to-upload/lib/cloudwatch-integration.js).

Expect a new version over the weekend, after some more testing.

**Comment by lazywithclass** [comment]
The test went fine, I run into a couple of issues but everything should be fine now.
I will test this a bit more and release the new version in a couple of days.

If you have any comments about the change just let me know.

**Comment by lazywithclass** [comment]
@bburket I've thought again about this, I think there is no real answer except creating a stream for each instance of the library, which then would mean:

 * bundling or requiring the aws cli to create groups / streams
 * leaving to the user the burden of collecting logs from multiple locations and ordering the log lines based on time

Or... accepting the fact that some logs might get lost, the apis are quite strict on upload speed and batch size, so at some point there is no solution if one have huge amount of logs.

What do you think?

**Comment by rickwaugh1** [comment]
?Hmm, just ran into this also. I'm using version 0.3.0. Is it definite that it's us exceeding the throughput
