### ISSUE TITLE
json format issue

### ISSUE THREAD

**Issue by aaaguirrep** [lazywithclass/winston-cloudwatch#125]
Hi, I have configured the transport with json format but it shows the next log in aws, I am sending an object in logger function:

Cloudwatch logs
`info - [object Object]`

Transport configuration:
```
	logger.add(new CloudWatchTransport({
		logGroupName: 'group-name',
		logStreamName: 'stream-name',
		awsRegion: 'us-east-1',
		jsonMessage: true
	}))
```

Logger
```logger.info({user: 'n/a', controller: 'n/a', function: 'logger', action: `start-${level}-mode`})```

Please, let me know if i need change the transport configuration.

Regards,
Arsenio

**Comment by lazywithclass** [comment]
Hello, to understand if you have everything correctly configured in AWS just use this example https://github.com/lazywithclass/winston-cloudwatch/blob/master/examples/function-config.js

If that works then you're ok AWS side, and your code is the problem, in that case I'd try to follow the examples and work from there.

Let me know how that goes.

**Comment by aaaguirrep** [comment]
Hi, thanks for your response I have reviewed the documentation and I fixed the code. At present I am seeing properly the log in cloudtrail.

**Comment by lazywithclass** [comment]
No problem.
