### ISSUE TITLE
Example Of Using IAM Roles

### ISSUE THREAD

**Issue by manjula1220** [lazywithclass/winston-cloudwatch#143]
I did not find any examples to use IAM Roles like to specify the IAM Role how we are specifying LogGroup, LogName Etc..

**Comment by lazywithclass** [comment]
Did you manage to solve this?

Have you tried specifying them in the `awsOptions` parameter https://github.com/lazywithclass/winston-cloudwatch/blob/master/examples/simple-with-aws-options.js#L10 ?
