### ISSUE TITLE
v2.5.1 release still contains the outdated version of proxy-agent (^3.1.1)

### ISSUE THREAD

**Issue by prestonlimlianjie** [lazywithclass/winston-cloudwatch#149]
I downloaded the v2.5.1 package from the [npm registry](https://registry.npmjs.org/winston-cloudwatch/-/winston-cloudwatch-2.5.1.tgz) and it seems like the `proxy-agent` dependency is still listed as `^3.1.1` instead of `^4.0.1`.

**Comment by wilhen01** [comment]
Same. Something isn't quite right...

**Comment by lazywithclass** [comment]
I'm not sure what I did there, I must've been too tired to publish, sorry about this mistake.

winston-cloudwatch@2.5.2 has proxy-agent@4.0.1
