### ISSUE TITLE
Help needed setting this up on lambda

### ISSUE THREAD

**Issue by aidan-ayala** [lazywithclass/winston-cloudwatch#152]
Does anyone have a working version of this being used on lambda or another serverless architecture?

I've tried using the kthxbye function to resolve a promise to ensure all logs are flushed before the lambda function exits but having no luck.

The example provided is fairly basic.

**Comment by lazywithclass** [comment]
Please provide a snippet of code that shows your problem so I can help.

**Comment by dyihoon90** [comment]
I know its closed but running into some issues with kthxbye on AWS Lambda.

When I run locally with serverless framework, the process exits fine. But when I deploy to AWS Lambda, my function executions are timing out.

In my function execution's aws logs (that does not require this winston-cloudwatch transport), "flushing logs" is logged, but "done" is not logged.

```typescript
async function main() {
  await exitLogger();
  console.log('done');
}

async function exitLogger(): Promise<void> {
  const winstonCloudWatchTransport = logger.winstonLogger.transports.find(
    (t) => (t as unknown as any).name === AWS_REPORTING_LOG_GROUP
  );
  if (winstonCloudWatchTransport) {
    await new Promise((resolve) => {
      logger.info('flushing logs');
      // kthxbye flushes remaining logs in the queue
      (winstonCloudWatchTransport as unknown as any).kthxbye(resolve);
    });
  }
  return;
}
```

**Comment by lazywithclass** [comment]
I will add some debugging information into `kthxbye` so that you could have some more hints on what is going on in your scenario.

I will try to deploy this weekend.

**Comment by lazywithclass** [comment]
winston-cloudwatch@3.0.2 pushed with more debugging info in `kthxbye`, please let me know if this helps you in understanding the problem.

**Comment by lazywithclass** [comment]
winston-cloudwatch@3.0.2 pushed with more debugging info in `kthxbye`, please let me know if this helps you in understanding the problem.
