### ISSUE TITLE
'name' does not exist in type 'CloudwatchTransportOptions'

### ISSUE THREAD

**Issue by SamsadSajid** [lazywithclass/winston-cloudwatch#155]
In your example for `flush-and-exit.js` the code uses a config `name` in the `WinstonCloudWatch` constructor. But the doc says there's no property called `name` in the options.

Here's your example:
```
var winston = require('winston'),
    WinstonCloudWatch = require('../index');

var self = winston.add(new WinstonCloudWatch({
  name: 'using-kthxbye',
  logGroupName: 'testing',
  logStreamName: 'another',
  awsRegion: 'us-east-1'
}));

winston.error('1');

// flushes the logs and clears setInterval
var transport = self.transports.find((t) => t.name === 'using-kthxbye')
transport.kthxbye(function() {
  console.log('bye');
});
```

Ref: https://github.com/lazywithclass/winston-cloudwatch/blob/master/examples/flush-and-exit.js

Is it obsolete now?

**Comment by lazywithclass** [comment]
I've probably just forgot to add `name` to the docs then, as it is being used https://github.com/lazywithclass/winston-cloudwatch/blob/master/index.js#L17

**Comment by chandora** [comment]
Do you have a plan to fix it?
For clarification, this is not just a doc error but also missing from TypeScript definition (winston-cloudwatch.d.ts).
Thank you,

**Comment by lazywithclass** [comment]
winston-cloudwatch@3.0.1 should have it fixed, I've added an example using TS so we can refer to that for further problems or features.

Please let me know if this fixes the issue for you.

**Comment by chandora** [comment]
I confirmed it.
Thank you for the prompt fix !

**Comment by lazywithclass** [comment]
Thanks to you for reminding me about this! :D

**Comment by abhimanusharma** [comment]
@lazywithclass I am using latest version 3.0.1 and still getting this error in typescript.

```
Argument of type '{ cloudWatchLogs: AWS.CloudWatchLogs; logGroupName: string; logStreamName: string; }' is not assignable to parameter of type 'CloudwatchTransportOptions'.
  Property 'name' is missing in type '{ cloudWatchLogs: AWS.CloudWatchLogs; logGroupName: string; logStreamName: string; }' but required in type 'CloudwatchTransportOptions'.ts(2345)
winston-cloudwatch.d.ts(54, 5): 'name' is declared here.
```

**Comment by lazywithclass** [comment]
Could you please show the code that's giving you this problem?

**Comment by JP-Dhabolt** [comment]
@lazywithclass Given that the name has a default value being assigned if not included in the options, shouldn't the Typescript definition declare name as optional?

Am currently using v3.0.0 of this library, but if updating to >=3.0.1, my existing (functional) code fails to compile, indicating that adding `name` as a required attribute is a breaking change.

I have been hesitant to update to the latest version, as a bugfix version bump with a breaking change usually indicates something isn't quite right.
