### ISSUE TITLE
Using aws-sdk v3 instead of v2 as dependency.

### ISSUE THREAD

**Issue by ajay47** [lazywithclass/winston-cloudwatch#160]
Currently this package uses aws-sdk v2 as dependency. Can you please look into the possibility of migrating over to v3. This will save a lot of space. The v3 is modular in nature and it will be beneficial for us to use @aws-sdk/client-cloudwatch-logs instead of v2 which imports all AWS service functions.
Please let me know if this is possible or maybe it can be scoped as part of Version 4 ? I am ready to help if you need any.
Thanks

**Comment by dicky1126277766238** [comment]
What a coincidence, I was going to raise this issue too. Yesterday, I just forked and modified for aws-sdk v3 for my own usage. You may take it as a reference. https://github.com/dicky1126277766238/winston-cloudwatch/commit/df4d90adfe6f53f3202e697ebf8cd9d4d3160599

It seems that support of v3 was considered in https://github.com/lazywithclass/winston-cloudwatch/issues/144#issuecomment-881712291 but finally gave up. I think the point of easy migration is using [v2 compatible style](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-cloudwatch-logs/index.html#v2-compatible-style) and use  [NodeHttpHandler](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/node-configuring-proxies.html) to config proxy. (Well I spent some time to figure out the proxy config)

**Comment by ajayttand** [comment]
@dicky1126277766238 Thank you. I was thinking of doing doing something like you have done.

**Comment by sagilevanon** [comment]
Much needed! All our code is based on v3 and adding the v2 is really bloating our bundle.

**Comment by lazywithclass** [comment]
Hello, sorry for the late reply, I have little to no time now to address issues, if you would like to submit PRs I am very open to review and merge.

**Comment by lazywithclass** [comment]
@dicky1126277766238 did you end up with some changes you'd feel comfortable to share as a PR here? I won't have time to do such a change.

**Comment by sagilevanon** [comment]
Hi @lazywithclass  - will you be able to merge #172 any time soon?
Having the whole `aws-sdk` is really bloating our package.

**Comment by lazywithclass** [comment]
winston-cloudwatch@3.2.0 is out
