### ISSUE TITLE
Suggest AMI Permissions

### ISSUE THREAD

**Issue by evantahler** [lazywithclass/winston-cloudwatch#166]
Hi! 

Can you please recommend the minimum AMI permissions that would be needed to use this library?  It looks like we are both reading and writing to Cloudwatch logGroups.

Thanks!

**Comment by mrdavidrees** [comment]
looking at the source, it should require these IAM permisions

DescribeLogStreams
CreateLogGroup
CreateLogStream
PutLogEvents
PutRetentionPolicy

**Comment by lazywithclass** [comment]
Yes it's like @mrdavidrees said.
