### ISSUE TITLE
Getting error cannot find module '@aws-sdk/client-cloudwatch-logs'

### ISSUE THREAD

**Issue by vishwanath-awate** [lazywithclass/winston-cloudwatch#179]
Hi,
I am suddenly getting error today "Cannot find module '@aws-sdk/client-cloudwatch-logs'".
Have you guys changed anything in your dependency ?

**Comment by lblo** [comment]
Same here. @aws-sdk/client-cloudwatch-logs should not be added as dev dependencies.

**Comment by danshirley1** [comment]
There are issues at GitHub atm?

**Comment by mikeallisonJS** [comment]
this caused a production headache today. I would assume this breaking dependency would have been a major version bump.

**Comment by kdjervbr** [comment]
Meanwhile I set `"winston-cloudwatch": "=3.1.1"` in package.json.

**Comment by danshirley1** [comment]
> Meanwhile I set `"winston-cloudwatch": "=3.1.1"` in package.json.

First thing I did also, just without the '='.

**Comment by lazywithclass** [comment]
Sorry about any problem the update did cause to your environments. I will look into this now.

**Comment by lazywithclass** [comment]
As per #180, you now need to have that dependency installed separately.

**Comment by lazywithclass** [comment]
I am going to republish this as v4.0.0 as it should've been in the first place.
