### ISSUE TITLE
Top level AWS credentials does not work anymore, but attached in docs

### ISSUE THREAD

**Issue by naufik** [lazywithclass/winston-cloudwatch#199]
**Issue**:

I have updated to `v6.0.1` from version `3.x` and had previously set up our transport as follows when using version `3.x`:

```js
new WinstonCloudwatch({
  awsAccessKeyId: "...",
  awsSecretKey: "...",
  awsRegion: "...",
});
```

This apparently has stopped working and we had to switch our configuration to follow your new example:
```js
new WinstonCloudwatch({
  awsOptions: {
    credentials: { ... },
    region: "..."
  }
});
```

While this may be expected. Your `README.md` still lists `awsAccessKeyId`, `awsSecretKey`, `awsRegion` under [Options](https://github.com/lazywithclass/winston-cloudwatch#options). Typescript typings also still contain those properties.

Could you please confirm whether this is a bug or the former is intentionally dropped off (in which case the docs should be updated)?

**Comment by lazywithclass** [comment]
Sorry for the confusion, the correct way is the second one as the docs and TS typings are outdated. I forgot to update them after a PR.

**Comment by naufik** [comment]
Thanks for the clarification, it's all good 👍🏽
