### ISSUE TITLE
Single log streams return not found even though they exist

### ISSUE THREAD

**Issue by typ90** [lazywithclass/winston-cloudwatch#22]
When trying to hook up a single log stream, line 71 of `cloudwatch-integration.js` checks for `matches/length` which returns false in the case that a single object is returned. 

In the case that a single log is matches, `_.find` returns a single object instead of an array and throws a false error that `Stream not found`.

**Comment by lazywithclass** [comment]
I am working on this.
I hope to provide a fix for tonight.

I decided to stop the work I was doing to address #11 since there seems to be an error now on the project due to me merging PRs without proper test.

**Comment by lazywithclass** [comment]
I have the fix, I will test it tomorrow at work and release a new version.

**Comment by lazywithclass** [comment]
Version 0.6.1 should address this.

I tested it and it works fine. Please let me know if it works also for you.
