### ISSUE TITLE
Readme should demonstrate jsonMessage option

### ISSUE THREAD

**Issue by traverseDLP** [lazywithclass/winston-cloudwatch#29]
It took a bit of digging to determine that I could enable json logging with `jsonMessage: true`. It would be awesome if you could add this to your readme or example.

**Comment by lazywithclass** [comment]
Is it better now?

**Comment by traverseDLP** [comment]
Much better! Thanks very much. You might want to put what kind of data types those options are looking for, but that's for you to decide.

**Comment by lazywithclass** [comment]
It makes sense for `jsonMessage` IMHO.
