### ISSUE TITLE
Create two loggers with different log level

### ISSUE THREAD

**Issue by tlcada** [lazywithclass/winston-cloudwatch#32]
Does anyone know that how this is possible:

var winston = require('winston');
var cloudwatch = require('winston-cloudwatch');

var errorLogs = winston.add(cloudwatch , {
    level: 'error',
    logGroupName: 'timetableprovider',
    logStreamName: 'error-logs',
    awsAccessKeyId: 'xxx-123',
    awsSecretKey: 'xxx-456',
    awsRegion: 'eu-central-1'
});

var infoLogs = winston.add(cloudwatch , {
    level: 'info',
    logGroupName: 'timetableprovider',
    logStreamName: 'info-logs',
    awsAccessKeyId: 'xxx-123',
    awsSecretKey: 'xxx-456',
    awsRegion: 'eu-central-1'
});

errorLogs.error('log this', { and: 'this too' });
infoLogs.info('log this', { and: 'this too' });

Problem is that I can not create two times winston.add(cloudwatch... because it gives an error "Transport already attached: CloudWatch".

**Comment by rebolyte** [comment]
Is it possible to have two loggers with different options at all? For me, the parameters of the last instance included are what gets used, so I can't set up different instances to log to different CloudWatch streams.

**Comment by lazywithclass** [comment]
It's not possible. I'm working on a solution right now.

**Comment by lazywithclass** [comment]
@rebolyte would something like this be helpful?

```javascript
winston.add(require('../index'), {
  logGroupName: 'test',
  logStreamName: 'stream1',
  awsRegion: 'us-east-1'
});
winston.error('error', { testing: 1 });

// changing the name allows for more transports
winston.add(require('../index'), {
  logGroupName: 'test',
  logStreamName: 'stream2',
  awsRegion: 'us-east-1',
  name: 'second-logger'
});
winston.error('error', { testing: 2 }, { name: 'second-logger' });
```

In the last line you would be passing the stream name as metadata.

**Comment by lazywithclass** [comment]
I've coded the feature but there's some issue with Winston (https://github.com/winstonjs/winston/issues/833), or probably with how I use it, that basically duplicates the entries I send to CloudWatchLogs.

The feature is "ready" in this branch if you fancy having a look at the problem https://github.com/lazywithclass/winston-cloudwatch/blob/using-multiple-configurations/index.js#L16

**Comment by rebolyte** [comment]
Thanks for the response. Yes, the the multiple loggers is the approach I'm trying now, but with the same problem. Ideally, I'd like to be able to use it like this:

```
winston.loggers.add('log1', {
    transports: [
        new winstonCloudwatch({
            logGroupName: 'test',
            logStreamName: 'testing',
            awsRegion: 'us-west-2',
            jsonMessage: true            
        })
    ]    
});
let log1 = winston.loggers.get('log1');

winston.loggers.add('handler2', {
    transports: [
        new winstonCloudwatch({
            logGroupName: 'test',
            logStreamName: 'testing2',
            awsRegion: 'us-west-2',
            jsonMessage: true            
        })
    ]    
});
let log2 = winston.loggers.get('log2');

log1.info('this gets logged to test/testing');

log2.info('this gets logged to test/testing2');
```

**Comment by lazywithclass** [comment]
I think I will have to convert it to use an OO approach.
I implemented a solution but it always logs to the last configured log.

**Comment by lazywithclass** [comment]
@rebolyte sorry I disappeared, I am working on it. In fact I just got the first working version. As you can imagine it's not really polished, so I will work cleaning it up and preparing a 1.0.0 with more tests than it has now (which are really poor).

This is how you would use it:

```javascript
winston.transports.CloudWatch1 = WinstonCloudWatch;
winston.transports.CloudWatch2 = WinstonCloudWatch;

winston.loggers.add('category1', {
  CloudWatch1: {
    logGroupName: 'test',
    logStreamName: '1'
  }
});
winston.loggers.add('category2', {
  CloudWatch2: {
    logGroupName: 'test',
    logStreamName: '2'
  }
});

winston.loggers.get('category1').error('1');
winston.loggers.get('category2').error('2');
```

I've tested and it works. Logging `"1"` and `"2"` to the proper streams.

**Comment by lazywithclass** [comment]
@tlcada @rebolyte I am done, if you want to test it you could use this branch https://github.com/lazywithclass/winston-cloudwatch/tree/using-multiple-configurations, I will publish 1.0.0 during the weekend.

**Comment by rebolyte** [comment]
Great! Tested and it works. Thanks for working on this.

**Comment by lazywithclass** [comment]
It's published, let me know if you're having problems and I'll try to fix in a quick iteration!
