### ISSUE TITLE
Limit of 5 clients per account due to frequent calls to describeLogStreams

### ISSUE THREAD

**Issue by rurri** [lazywithclass/winston-cloudwatch#42]
AWS limits calls to describeLogStreams to 5 times per second per account per region.

Because this software calls describeLogStreams *twice* per log put request. The default setting of using an uploadRate of 2 seconds causes ThrottlingException to occur after just 5 clients are using this transport--even if each user of this library is putting logs to a different stream.

The putLogEvents also has this limit, but it is per *stream* not a limit per *account* thus multiple applications can still use it.

A group that has more than one application and multiple stages for each app running will quickly exhaust this limit, and this error will start occurring once just 5 clients are using this library, even if they are on different log streams.

Suggested improvement:

- Only call describe stream on initial start to obtain the sequence number and/or create the log stream.
- Keep the sequence number from put requests (returned as nextSequenceToken from each log send event
- In the event of an "Invalid Sequence Number" error then describe the logs again to get a fresh sequence number

```
{ [ThrottlingException: Rate exceeded]
  message: 'Rate exceeded',
  code: 'ThrottlingException',
  time: Sat Aug 06 2016 23:20:24 GMT+0900 (KST),
  requestId: 'ea97610e-5be0-11e6-98c4-899b2d2520f0',
  statusCode: 400,
  retryable: true }
```

**Comment by lazywithclass** [comment]
Hey @rurri thanks for taking the time to create this issue, seems like I need to revisit quite a few parts of the library.

Sorry it took so much for me to answer, I am looking into the best course of action for your valid points.

I'll first have a look at https://github.com/lazywithclass/winston-cloudwatch/pull/43 and then come back to this after that is merged.

**Comment by lazywithclass** [comment]
About your points:

1. "Only call describe stream on initial start to obtain the sequence number and/or create the log stream." - I need to create the log stream whenever there's the need for a new log to be uploaded, the user might've asked for a new stream. Also it might happen that a stream gets deleted while the app is running, logging has to still work.
2. "Keep the sequence number from put requests (returned as nextSequenceToken from each log send event)" - I will add this as task, thanks
3. "In the event of an "Invalid Sequence Number" error then describe the logs again to get a fresh sequence number" - I will add this as task, thanks
