### ISSUE TITLE
ERROR: self.logStreamName - self is not defined

### ISSUE THREAD

**Issue by laurieb** [lazywithclass/winston-cloudwatch#56]
Hi,

I believe a change to your package has caused my servers to crash today.... :-)

My new servers that were started up by elastic beanstalk today were all crashing with this error

```
{
  "level": "warn",
  "message": "Running in dev environment, no Authorization."
}
/Users/lauriebantin/Documents/dyzio/git/holidayextras/dyzio-server/node_modules/winston-cloudwatch/index.js:112
    self.logStreamName() : this.logStreamName;
    ^

ReferenceError: self is not defined
    at WinstonCloudWatch.submit (/Users/lauriebantin/Documents/dyzio/git/holidayextras/dyzio-server/node_modules/winston-cloudwatch/index.js:112:5)
    at Timeout._repeat (/Users/lauriebantin/Documents/dyzio/git/holidayextras/dyzio-server/node_modules/winston-cloudwatch/index.js:98:12)
    at Timeout.wrapper [as _onTimeout] (timers.js:417:11)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

I'm going to lock the package to an older version for now, but I thought you might need the feedback.

The code + environment all worked perfectly before this.

Thanks
Laurie

**Comment by laurieb** [comment]
@lazywithclass Yes, the servers all picked up v1.11.0 today. I've reverted back to 1.10.0 and it seems to have fixed that problem.

Thanks for your prompt help! 👍

**Comment by lazywithclass** [comment]
1.11.1 available @laurieb, so much for not using a refactor command and doing the change by hand :(

**Comment by laurieb** [comment]
BTW, have you seen this warning?

```
the server/replset/mongos options are deprecated, all their options are supported at the top level of the options object [poolSize,ssl,sslValidate,sslCA,sslCert,sslKey,sslPass,sslCRL,autoReconnect,noDelay,keepAlive,connectTimeoutMS,socketTimeoutMS,reconnectTries,reconnectInterval,ha,haInterval,replicaSet,secondaryAcceptableLatencyMS,acceptableLatencyMS,connectWithNoPrimary,authSource,w,wtimeout,j,forceServerObjectId,serializeFunctions,ignoreUndefined,raw,promoteLongs,bufferMaxEntries,readPreference,pkFactory,promiseLibrary,readConcern,maxStalenessSeconds,loggerLevel,logger,promoteValues,promoteBuffers,promoteLongs,domainsEnabled,keepAliveInitialDelay,checkServerIdentity,validateOptions]
```

http://stackoverflow.com/questions/42409258/warning-after-updating-mongodb-dependency

The warnings worry me a bit, is this to do with a package you are using? I don't think it's in my app, but not sure...

**Comment by lazywithclass** [comment]
I've never seen it when running winston-cloudwatch. I'm not sure it's a package I'm using, I don't have mongo dependencies. I will have a look and see if that's correct.

When do you see that warning?

**Comment by laurieb** [comment]
Hi @lazywithclass 

v1.11.1 runs fine locally - just about to deploy to servers

Don't worry about the above warning - I doubt your package uses mongodb

**Comment by lazywithclass** [comment]
Ok, let me know.

**Comment by lazywithclass** [comment]
@laurieb Should I close this?

**Comment by laurieb** [comment]
Yes, please close; v1.11.1 is doing great!!!
