### ISSUE TITLE
Allow AWS to be passed in as option

### ISSUE THREAD

**Issue by jd-carroll** [lazywithclass/winston-cloudwatch#57]
In our environment we need to set the proxy for certain requests, but un-set the proxy when working with AWS.  Additionally, we will pin/modify the AWS SDK to meet specific requirements internally.

It would be nice if we could pass `AWS` as a config param, and update the code to the following:
```
    if (!options.AWS && this.proxyServer) {
        AWS.config.update({
            httpOptions: {
                agent: require('proxy-agent')(this.proxyServer)
            }
        });
    } else if (options.AWS) {
        AWS = options.AWS;
    }
```

**Comment by lazywithclass** [comment]
Ok, I think this could be useful for others too, feel free to suggest a PR.
