### ISSUE TITLE
Non-enumerable meta objects not being serialized

### ISSUE THREAD

**Issue by SteveWestbrook** [lazywithclass/winston-cloudwatch#65]
A common use of winston is to record error information using

`logger.error('It failed for some reason', err);`

where `logger` is a winston instance and `err` is some Error instance.  Unfortunately, on inspecting cloudwatch logs, we found that this error information was not transmitted, and instead was replaced with an empty object.  A little digging in the winston-cloudwatch codebase led to line 3 of lib/utils.js, which controls serialization:

`function stringify(o) { return JSON.stringify(o, null, '  '); }`

Unfortunately JSON.stringify does not serialize non-enumerable members, and so all members of the Error instance are lost.

Other winston transports (console, file, etc.) do successfully serialize errors using different means.

There is a [good discussion on SO](https://stackoverflow.com/questions/18391212/is-it-not-possible-to-stringify-an-error-using-json-stringify) about this issue and possible workarounds.

Edit: it looks like winston's default transports treat errors as a special case by recording only their `stack` property.

**Comment by lazywithclass** [comment]
@SteveWestbrook thanks a lot for the detailed issue. I had no idea about `JSON.stringify` not serialising non-enumerable members, that SO question is great, I am now implementing the fix as follows:

```JS
function replaceErrors(key, value) {
    if (value instanceof Error) {
        var error = {};

        Object.getOwnPropertyNames(value).forEach(function (key) {
            error[key] = value[key];
        });

        return error;
    }

    return value;
}
```

**Comment by lazywithclass** [comment]
@SteveWestbrook The problem was a funny combination of what you've correctly written and the way `lodash.isEmpty(new Error('uh-oh))` works, from [the docs](https://lodash.com/docs/4.17.4#isEmpty):

> Objects are considered empty if they have no own enumerable string keyed properties.

This is the visual result, is it what you wanted?

![image](http://i.imgur.com/BQH50vi.png)

I'd love another pair of eyes to check my solution, could you please have a look at https://github.com/lazywithclass/winston-cloudwatch/compare/stringify-handles-error-objects

**Comment by SteveWestbrook** [comment]
Looks good to me.

If you value one-to-one behaviour match with winston's default transports, you can just take error.stack instead of serializing the whole error, but I like your solution better.

I was wondering if it were possible to assign data to an error such that it will not show up in Object.getOwnPropertyNames, but a basic assignment does not cause any problems for your code, so I am not too concerned.

Nice catch on the lodash implementation.  I liked your unit tests as well.

**Comment by lazywithclass** [comment]
winston-cloudwatch@1.11.4 is now available, thanks for finding this issue
