### ISSUE TITLE
Question:  How to debug?

### ISSUE THREAD

**Issue by lukewis** [lazywithclass/winston-cloudwatch#77]
I'm certain I'm missing something obvious here, but my simple example doesn't behave as expected.  My experience with AWS is that it's nearly always a permissions issue, but in this case it doesn't appear that the events are even attempted to be written to cloudwatch.  I tried setting WINSTON_CLOUDWATCH_DEBUG=true, but I didn't see any additional output.  The LogGroup and LogStream exist in AWS and my ~/.aws/credentials file should have access to write to them.

````
let winston = require("winston");
let WinstonCloudWatch = require("winston-aws-cloudwatch");

var tmp = winston.add(WinstonCloudWatch, {
    name: "CloudWatch",
    logGroupName: 'Foo',
    logStreamName: 'Bar'
  });
  
  tmp.on('logging', (transport, level, msg, meta) => {
    console.log(`The ${transport.name} transport did log`);
  });
  tmp.on('error', (err) => {
    console.log(`The logger did error: ${err}`);
  });
  winston.error('1');
````
And the output I see from this is:
`error: 1`
`The console transport did log`

I would have expected to see something regarding the CloudWatch transport (even if it's an error).  Any ideas what I'm doing wrong or how to get more debug info?

**Comment by lukewis** [comment]
Nevermind.  It WAS an obvious mistake.....I had confused this npm package with winston-aws-cloudwatch.  Yours works just fine.

**Comment by lazywithclass** [comment]
Ok cool 👍
