### ISSUE TITLE
Meta data braces always showing

### ISSUE THREAD

**Issue by rickwaugh1** [lazywithclass/winston-cloudwatch#8]
Minor issue. If I send no meta data, {...and this}, I still get the empty braces showing up in cloudwatch. 

2015-02-13 18:26:59 UTC info - Environment dev listening on 8081... - {}

**Comment by lazywithclass** [comment]
Yes, I saw that, is it causing problems to you? 
For example because you parse it in some way expecting something if the curly braces are there?

**Comment by rickwaugh1** [comment]
No, simple esthetics. :D Not a problem at all.

On 2015-03-03 3:28 AM, Alberto Zaccagni wrote:
>
> Yes, I saw that, is it causing problems to you?
> For example because you parse it in some way expecting something if 
> the curly braces are there?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/lazywithclass/winston-cloudwatch/issues/8#issuecomment-76929106>.
>

-- 
Server Developer
Finger Food Studios Inc.
tel: 604-475-0350
email: rick@fingerfoodstudios.com

skype: rick.waugh4

www.fingerfoodstudios.com

MESSAGES / COMMENTS This message is intended for the use of the individual or entity to which it is addressed and may contain information that is privileged, confidential and exempt from disclosure under applicable law. If the reader of this message is not the intended recipient, or the employee or agent responsible for delivering the message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify us immediately and return the original message to us at the above address. Thank you.

**Comment by lazywithclass** [comment]
Ok then thanks for pointing that out, but if we are fine with having it this way I'll mark the issue as wontfix.
