### ISSUE TITLE
Typescript 'silent' property is missing.

### ISSUE THREAD

**Issue by Rickgg** [lazywithclass/winston-cloudwatch#83]
Typescript is giving an error that the `silent` property is missing in the `TransportInstance` options. According to the docs, the property is used only in 6 transports, not sure if the module can/should support it too.

**Comment by lazywithclass** [comment]
We don't explicitly support it. Have a look [at this line](https://github.com/lazywithclass/winston-cloudwatch/blob/master/index.js#L13), there we call the `Transport` with `options`.

I can add it to the TypeScript definition, would that be ok?

**Comment by Rickgg** [comment]
Yes please, at least so that the TS compiler doesn't throw error.

**Comment by lazywithclass** [comment]
I will, as part of the improvements that will come after Winston 3.0 (which should be released today).

**Comment by Rickgg** [comment]
Great! Thanks.

**Comment by lazywithclass** [comment]
@Rickgg You will find it in v2.0.1, sorry for the horrific delay!

**Comment by Rickgg** [comment]
Don't worry about it, and thank you very much!
