### ISSUE TITLE
InvalidSequenceTokenException: The given sequenceToken is invalid.

### ISSUE THREAD

**Issue by jawadakram20** [lazywithclass/winston-cloudwatch#84]
I am getting this error when I try to add logs to cloudwatch using my nodejs app which is running in cluster mode. Couldn't find any solution. Please respond asap.

**Comment by jawadakram20** [comment]
@lazywithclass

**Comment by lazywithclass** [comment]
With the information you have me it's almost impossible to reproduce the issue. 

* are you using a different stream per resource? Have a look at the [AWS docs](https://github.com/lazywithclass/winston-cloudwatch#usage)
 * did you try reproducing the issue with the minimum code possible? [Simulation](https://github.com/lazywithclass/winston-cloudwatch#simulation) might help you
 * what version of the library are you using?

**Comment by jawadakram20** [comment]
@lazywithclass I am using
`"winston": "^2.4.3", "winston-cloudwatch": "^1.13.1"`

my code is...

`import * as winston from 'winston';
import { environment } from '../../config/environment';
import 'winston-cloudwatch';

const options: winston.CloudwatchTransportOptions = {
  logGroupName: (environment.NODE_ENV || 'development'),
  logStreamName: (environment.NODE_ENV ? `${environment.NODE_ENV}` : 'development'),
  awsRegion:  (environment.AWS_CLOUDWATCH_REGION || 'us-east-1'),
  awsAccessKeyId: environment.AWS_CLOUDWATCH_ACCESS_KEY_ID,
  awsSecretKey: environment.AWS_CLOUDWATCH_SECRET_ACCESS_KEY,
  jsonMessage: true
};

winston.handleExceptions(new winston.transports.Console({
  json: true,
  timestamp: true,
  colorize: true,
  level: 'error',
}));

class Logger {
  logger: winston.LoggerInstance;
  constructor() {
    const transports = [];
    if (!environment.isTest()) {
      transports.push(new (winston.transports.CloudWatch)({
        json: true,
        timestamp: true,
        colorize: true,
        handleExceptions: true,
        humanReadableUnhandledException: true,
        name: 'info',
        level: 'info',
        ...options
      }));
      transports.push(new (winston.transports.CloudWatch)({
        json: true,
        timestamp: true,
        handleExceptions: true,
        colorize: true,
        name: 'error',
        humanReadableUnhandledException: true,
        level: 'error',
        ...options
      }));
    }
    if (!environment.isProduction()) {
      transports.push(new winston.transports.Console({
        json: true,
        timestamp: true,
        colorize: true,
        level: 'debug',
      }));
    }
    this.logger = new (winston.Logger)({
      transports,
    });
  }`

**Comment by lazywithclass** [comment]
What about the other questions? What results did you get by running the simulation?

Your code looks fine, but I might be wrong since it's not formatted, I am sure you can simplify it more than this, to arrive to "the minimum code possible" I was talking about before. Once you arrive to that we could see if there's a bug or not, my guess is that you're using a single stream.

**Comment by jawadakram20** [comment]
@lazywithclass yeah, I am using single stream but when I create multiple streams I donot get that error. also nothing logged on cloudwatch as well.

**Comment by lazywithclass** [comment]
That's the point of my first question

> are you using a different stream per resource? Have a look at the AWS docs

You should use one stream per resource.
You should run the simulation and see if that works, from there you know that your setup in AWS works, and you can check if the works, after you've reduced your code to the minimum (no dev / production checks, no config that's not strictly necessary, etc) please paste it here.

**Comment by lazywithclass** [comment]
That code is not logging though, right? I mean, it's missing the logging line.

Try to run one of [the examples](https://github.com/lazywithclass/winston-cloudwatch/tree/master/examples) and see if you still get an error.

**Comment by jawadakram20** [comment]
@lazywithclass I am logging with

`logger.info('this is first log.');`

**Comment by lazywithclass** [comment]
Ok. I've never used it with TypeScript, but we can easily see where the problem is if you either run

 * the simulation
 * one of the examples

Once you've run one of those, we will have a clearer understanding of where the problem is.

**Comment by jawadakram20** [comment]
@lazywithclass I have used your code of simulation.
It logs nothing on cloudewatch as I am using dynamic stream names.

```var winston = require('winston');
    WinstonCloudwatch = require('winston-cloudwatch'),
    bcrypt = require('bcrypt-nodejs');
    const { environment } = require('../../../dist/config/environment');

// Give ourselves a randomized (time-based) hash to append to our stream name
// so multiple instances of the server running don't log to the same
// date-separated stream.
const options = {
  logGroupName: 'development',
  awsRegion:  'us-east-1',
  awsAccessKeyId: environment.AWS_CLOUDWATCH_ACCESS_KEY_ID,
  awsSecretKey: environment.AWS_CLOUDWATCH_SECRET_ACCESS_KEY,
};

console.log(options);

winston.loggers.add('access-log', {
  transports: [
    new winston.transports.Console({
      json: true,
      colorize: true,
      level: 'info'
    }),
    new WinstonCloudwatch({
      logGroupName: 'development',
      logStreamName: function() {
        // Spread log streams across dates as the server stays up
        let date = new Date().toISOString().split('T')[0];
        return 'express-server-' + date + '-' +
          bcrypt.hashSync('password', bcrypt.genSaltSync(8));
      },
      ...options,
      jsonMessage: true
    })
  ]
});
var logg = winston.loggers.get('access-log');

logg.info('This is a test');
```

**Comment by lazywithclass** [comment]
I don't see the problem here, just use a fixed name. 
We are testing if the library works and your infrastructure is correctly configured.

**Comment by jawadakram20** [comment]
@lazywithclass I have used the fixed name as well. But nothing worked for me :(

**Comment by lazywithclass** [comment]
I see. Well, consider that the following should definitely work: https://github.com/lazywithclass/winston-cloudwatch/blob/master/examples/simple.js

At a minimum you have to get that working.

**Comment by jawadakram20** [comment]
I have used minimum code and it didnt work at all as well.

```
var winston = require('winston');
    
const WinstonCloudwatch = require('winston-cloudwatch');

const { environment } = require('../../../dist/config/environment');


// when you don't provide a name the default one
// is CloudWatch
winston.add(WinstonCloudwatch, {
  logGroupName: 'development',
  awsRegion:  'us-east-1',
  awsAccessKeyId: environment.AWS_CLOUDWATCH_ACCESS_KEY_ID,
  awsSecretKey: environment.AWS_CLOUDWATCH_SECRET_ACCESS_KEY,
  logStreamName: 'development-info',
  jsonMessage: true
});

winston.error('1');
```

Do I need to change anythuing on my aws console as well because I have given cloudbasefullacess to my IAM user.

**Comment by lazywithclass** [comment]
If you're unsure about your configuration on AWS then you have to do an extra step back: try with the command line https://docs.aws.amazon.com/cli/latest/reference/logs/put-log-events.html

That way you're sure you have nothing between you and AWS.

I don't have any experience with cloudbase sorry. I would take small steps first trying to access directly to AWS CloudWatch from your laptop.

**Comment by jawadakram20** [comment]
@lazywithclass This is working for me now. Just one thing that does this package retry whenever an exception of sequenceToken is raised automatically or we have to handle that programmatically?
Also is there any options while using that we can create new streams from code on aws?

**Comment by lazywithclass** [comment]
Whenever we either get `InvalidSequenceTokenException` or `ResourceNotFoundException` we retry, [as you can see here](https://github.com/lazywithclass/winston-cloudwatch/blob/master/lib/cloudwatch-integration.js#L80).

About the streams, yes, if the stream, or the group, is not there the library will create it for you. 

Can I close this then?

**Comment by jawadakram20** [comment]
@lazywithclass The library does not create the stream for me.

**Comment by jawadakram20** [comment]
@lazywithclass closing this as everything is working now. Thanks... You can add my typescript code as well as an example of typescript too.

**Comment by kevde** [comment]
I have updated my latest version on my winston cloudwatch. This implementation still doesnt work. I tried to programatically call putEventLogs and the saving of log event work if a sequence token is assigned, There is no example here in winston-cloudwatch about this. At the same time I dont know how to attach the sequence token on the code. It is essential in logging

**Comment by lazywithclass** [comment]
Could you provide some code showing the problem you're having?
