### ISSUE TITLE
v2.x on npm?

### ISSUE THREAD

**Issue by deyhle** [lazywithclass/winston-cloudwatch#85]
When will version 2.x with support for winston 3 be released on npm? It's still having 1.13.1 as `latest`.

**Comment by lazywithclass** [comment]
Yes I did some tests during the weekend and all seems good. I am just being extra careful, sorry about the delay.

**Comment by lazywithclass** [comment]
@nfantone @ patrickrgaffney I am sometimes getting `"ExpiredTokenException: The security token included in the request is expired"`.

Is this happenning to you? Could you please share how you're using winston-cloudwatch with winston 3.0?

**Comment by lazywithclass** [comment]
I am going a bit longer with this. I'm making sure also the examples are all correct for the sake of documentation.

**Comment by patrickrgaffney** [comment]
I have yet to actually point back to this repository instead of my fork that was discussed on #76. I'll make an attempt to update these dependencies sometime this week and report back my findings.

**Comment by lazywithclass** [comment]
Ok @patrickrgaffney, thanks!

**Comment by lazywithclass** [comment]
Just an update: I've updated all examples to use the latest API. Next up is the simulation tool, some more testing, then I'll publish as beta. Sorry for the delay :b

**Comment by lazywithclass** [comment]
I pushed version 2.0

Thanks for all the help and the bug reports. I expect there will be some small problems (one already know is https://github.com/lazywithclass/winston-cloudwatch/issues/1). Any further help with PRs or detailed bug reports is more than welcome.
