### ISSUE TITLE
When logging with exception the message is not passed through

### ISSUE THREAD

**Issue by lazywithclass** [lazywithclass/winston-cloudwatch#88]
For example in the following

```
winston.add(new WinstonCloudWatch({
  logGroupName: 'error-group-name',
  logStreamName: 'error-stream-name',
  awsRegion: 'us-east-1'
}))

var error = new Error('we are doooooomed!')
winston.error('error', error)
```

We don't send `'we are doooooomed!'`.

Unless we do 

```
winston.error(error)
```

instead. Still have to understand if it's a bug or it's ok.

**Comment by lazywithclass** [comment]
@nfantone / @patrickrgaffney was this happening to you?

**Comment by deyhle** [comment]
JSON.stringify of an Error object always results in '{}' in Node.js, so I'd say it is ok. Unless you want to define a default behavior of JSON-ifing Error objects so users don't have to think about that.

**Comment by lazywithclass** [comment]
This should be handled.
