### ISSUE TITLE
Time out error

### ISSUE THREAD

**Issue by ananddevsingh** [lazywithclass/winston-cloudwatch#92]
Hi Team,
I'm trying below code with lambda function for the Alexa skill.
`const winston = require('winston');
const WinstonCloudWatch = require('winston-cloudwatch');

const singleLogger = winston.createLogger({
  transports: [
    new WinstonCloudWatch({
      name: 'first-stream',
      logGroupName: 'testing',
      logStreamName: 'first',
      awsRegion: 'us-east-1'
    })
  ]
});`
After the implementation of error or info etc methods, it starts throwing timeout error. 

`singleLogger.error('This is  error by Winston.');`

However, while using "**log**" method
`singleLogger.log('This is log by Winston.');`

It is throwing below error:

`{
  "errorMessage": "Cannot create property 'Symbol(level)' on string 'log by winston.'",
  "errorType": "TypeError",
  "stackTrace": [
    "Object.<anonymous> (/var/task/index.js:22:14)",
    "Module._compile (module.js:652:30)",
    "Object.Module._extensions..js (module.js:663:10)",
    "Module.load (module.js:565:32)",
    "tryModuleLoad (module.js:505:12)",
    "Function.Module._load (module.js:497:3)",
    "Module.require (module.js:596:17)",
    "require (internal/module.js:11:18)"
  ]
}`

Please help me with some example that can get me rid of the error:

**Comment by lazywithclass** [comment]
Hello @ananddevsingh, did you try having a look at [the examples](https://github.com/lazywithclass/winston-cloudwatch/tree/master/examples)?

**Comment by ananddevsingh** [comment]
Yes, I've already gone thru all the examples but none has worked for me.

**Comment by lazywithclass** [comment]
That's a problem, I would start with [this one](https://github.com/lazywithclass/winston-cloudwatch/blob/master/examples/simple.js), please run it and tell me how it goes.
